version: "3"

services:
  rocketchat:
    image: wernight/phantomjs:latest
    ports:
      - "8080:8910"
    entrypoint:
      - phantomjs
      - --webdriver=8910
      - --ignore-ssl-errors=true
      - --load-images=false
      - --webdriver=8910

